Feature/sif 1 navigation
TeamSaifu/Saifu_Flutter pull request #3
Opened 2021-04-15 08:24 UTC by tachibana687

ナビゲーションバーを作成した
page.dartはサンプルページとして使用したので使わなくていいです

2021-04-15 10:17 UTC, tak-st commented
＋51000って何？？

2021-04-15 10:21 UTC, tak-st requested changes
不要なファイルをアップロードしてるっぽい？ので次の月曜にどのファイルが不要かを確認する予定

2021-04-16 00:51 UTC, kamatamaudon3 approved these changes

2021-04-16 02:56 UTC, tak-st approved these changes
おっけー

2021-04-16 03:25 UTC, ecccomp123 approved these changes

2021-04-16 03:30 UTC, Toyoda9 approved these changes
見ました

2021-04-16 03:34 UTC, merged