SIF-7 データベースを作成しました。
TeamSaifu/Saifu_Flutter pull request #7
Opened 2021-04-30 07:29 UTC by kamatamaudon3

## 概要
データベースを作成しました。

## 保留している作業
作成しただけなのでデータは格納されていません。

2021-04-30 07:31 UTC, tak-st requested changes
他のテーブルも追加してください。

2021-04-30 07:36 UTC, ecccomp123 approved these changes

2021-05-03 05:00 UTC, tak-st reviewed
不要なreturn

2021-05-03 05:00 UTC, tak-st commented on lib/database.dart
> +    return databese;
```suggestion
```

2021-05-03 05:03 UTC, tak-st approved these changes
問題なさそう

2021-05-03 05:23 UTC, tachibana687 approved these changes

2021-05-03 05:23 UTC, tachibana687 approved these changes
おっけー

2021-05-07 03:08 UTC, merged